version: "3.5"

services: 
    batbot:
        container_name: BatBot
        build:
            context: ./
            dockerfile: ./Dockerfile
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
